version: '3.8'

services:
  backend1:
    build: ./admin
    ports:
      - "8081:8081"
    volumes:
      - ./admin:/app
      - ./certs:/certs
    environment:
      - PORT=8081

  backend2:
    build: ./admin
    ports:
      - "8082:8082"
    volumes:
      - ./admin:/app
      - ./certs:/certs
    environment:
      - PORT=8082

  backend3:
    build: ./admin
    ports:
      - "8083:8083"
    volumes:
      - ./admin:/app
      - ./certs:/certs
    environment:
      - PORT=8083

  backend4:
    build: ./admin
    ports:
      - "8084:8084"
    volumes:
      - ./admin:/app
      - ./certs:/certs
    environment:
      - PORT=8084

  backend5:
    build: ./admin
    ports:
      - "8085:8085"
    volumes:
      - ./admin:/app
      - ./certs:/certs
    environment:
      - PORT=8085

  catalog:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - ./certs:/certs
    environment:
      - PORT=3000

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - backend1
      - backend2
      - backend3
      - catalog
